# Generated by Django 3.2.3 on 2021-05-25 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AF', 'A fazer'), ('FF', 'Feito'), ('AR', 'Atualizar'), ('AO', 'Atualizado')], max_length=2)),
                ('last_updated', models.DateField(auto_now=True)),
                ('category', models.CharField(max_length=150)),
                ('product', models.CharField(choices=[('CE', 'Celero'), ('ST', 'Start'), ('FW', 'Flow')], max_length=2)),
                ('is_deleted', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
